Test1 pull request template
opencodeiiita/opencodebot pull request #36
Opened 2019-01-17 18:19 UTC by littleprodigy

2019-01-18 13:17 UTC, DreamyPhobic requested changes

2019-01-18 13:17 UTC, DreamyPhobic commented on .github/pull_request_template.md
> +Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
add these lines as comment.

2019-01-18 13:17 UTC, DreamyPhobic commented on .github/pull_request_template.md
> +Please delete options that are not relevant.
this

2019-01-18 13:17 UTC, DreamyPhobic commented on .github/pull_request_template.md
> +Please provide screenshots to get the mentor know easily about the changes you have made and how well is it working now?
this

2019-01-18 13:17 UTC, DreamyPhobic commented on .github/pull_request_template.md
> +Please describe any relevant performance impact of this change. This can be positive or negative impact. How did you characterize/test the performance impact?
and this

2019-01-21 18:28 UTC, aasthakasera commented
Kindly check it.

2019-01-22 13:23 UTC, merged