Test2  Issue Template
opencodeiiita/opencodebot pull request #37
Opened 2019-01-17 18:50 UTC by littleprodigy

2019-01-18 13:15 UTC, DreamyPhobic requested changes

2019-01-18 13:15 UTC, DreamyPhobic commented on .github/ISSUE_TEMPLATE.md
> +# Issue Template
remove this line...

2019-01-18 13:15 UTC, DreamyPhobic commented on .github/ISSUE_TEMPLATE.md
> +Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
add this as a comment.

2019-01-18 13:15 UTC, DreamyPhobic commented on .github/ISSUE_TEMPLATE.md
> +Please describe the behavior you are expecting
this one also as a comment.

2019-01-18 13:15 UTC, DreamyPhobic commented on .github/ISSUE_TEMPLATE.md
> +What is the current behavior?
this too.

2019-01-18 13:15 UTC, DreamyPhobic commented on .github/ISSUE_TEMPLATE.md
> +What is the current behavior?
Basically all text after title sub title should be comment.

2019-01-21 16:22 UTC, littleprodigy commented on .github/ISSUE_TEMPLATE.md
> +Please describe the behavior you are expecting
Kindly, give some hint.

2019-01-21 18:26 UTC, aasthakasera commented
Changes have been made , check it.

2019-01-22 13:23 UTC, merged